[package]
name = "vectis-webauthn-authenticator"
version = "0.1.0"
authors = ["bwty <whalelephant@users.noreply.github.com>", "j0nl1 <j0nl1@gmail.com>"]
edition = "2021"

exclude = [
  "contract.wasm",
  "hash.txt",
]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies]
cosmwasm-std = { version = "1.2", features = ["iterator", "ibc3", "staking", "cosmwasm_1_2"] }
cosmwasm-storage = "1.2" 
cosmwasm-schema = "1.2" 
sylvia = "0.7.0"
sylvia-derive = "0.7.0"
cw2 = "1.1"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-json-wasm = "0.5.1"
sha2 = "0.9"
ripemd160 = "0.9.1"
p256 = {version = "0.13.2", default-features = false, features = ["alloc", "ecdsa-core"]}
vectis-wallet = { path = "../../../packages/vectis" }
# cosmwasm-std.workspace = true
# cosmwasm-storage.workspace = true
# cosmwasm-schema.workspace = true
# sylvia.workspace = true
# sylvia-derive.workspace = true
# cw-storage-plus.workspace = true
# cw2.workspace = true
# anyhow.workspace = true
# serde.workspace = true
# serde-json-wasm.workspace = true
# sha2 = "0.9"
# ripemd160 = "0.9.1"
# # base64ct = {version = "1.6.0", default-features = false, features = ["alloc"] }

[dev-dependencies]
cw-multi-test = "0.16"
